### PR TITLE
Visualize the difference in healthy and unhealthy gene expression 

### PR DESCRIPTION
**Pull request by ben-heil**
This PR adds a notebook that visualizes various subsets of the gene expression data being used in this repo. 

Takeaways:
- In general, gene expression is far more similar between samples from the same study than across studies (as you would expect due to batch effects)
- This effect is so strong that healthy samples from a study are more similar to unhealthy samples from the same study than to healthy samples from other studies
- Transformation with PLIER does little to change the observations above

None of these results are particularly surprising, but they make the importance of finding a good representation for the gene expression very clear. Since the studies are all distinct in raw (row normalized) gene expression space, working in gene set or biological network space will be necessary.

### CODE REVIEW

**Comment by arielah** [comment]
Having trouble making inline comments on the notebook. For block [7], the last one under load and prepare data, you should include a note about why you're creating a column called "is_SRP048759". Is that study used as an example, or is it behaving differently and needs to be treated differently?

**Comment by arielah** [comment]
Block [8] and down: For clarity, I would change the axis labels from "x" and "y" to something like 'UMAP dimension 1' and 'UMAP dimension 2'. x and y made my mind go automatically to dependent and independent variables, which is obviously not what's going on here.

**Comment by arielah** [comment]
Block [10] and down: now I can see that block[7] is initiating a form of one-hot encoding for your examples. I'd just be clear about them being examples and why you're picking those studies (they're representative vs. randomly selected, etc.)

**Comment by arielah** [comment]
Looks good overall. The conclusions section at the end of each analysis is helpful for a lay user to understand what the data are saying. I would just be very explicit about when you're looking at the data altogether and when you're pulling out an example study.

**Review by arielah — APPROVED** [review]

**Comment by ben-heil** [comment]
Good catch, I pulled out specific studies towards the beginning because they were very diffuse compared to other studies. I added the column required to highlight them as part of the data loading process because it made sense to add columns while creating the dataframe, but I didn't think about how that wouldn't make sense chronologically.

**Pull request merged**
